# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f7540c673ae6d605bc2d0b464ef732e405f12261a7cce1c7f517b956160873cd0379dc6da6baf148774cdb03d5b6e98a2626cd55aba669c4c5a4b12e4414068

test:
  secret_key_base: 2b018612a1025ee092155e6d981989c5e9463ddc25a03300ea3e4b834e94567fe92cd85cb051b78e0ccc4d0ca9036f2fc3b80783d3e3a0674066b6093ac56a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
